language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php -- --quiet
    - php composer.phar install --dev --prefer-source --no-interaction